### PR TITLE
Add CDDL stuff

### PR DESCRIPTION
**Pull request by fluffy**
I have no idea if we should add this or not. Thoughts on if we should. This text comes from a patch Carsten sent.

### CODE REVIEW

**Comment by cabo** [comment]
That is CDDL for the old version (with the "e" key and everything).
Once we have a clear idea where we are going with the top-level arrays, I can adapt this very quickly.
(I'd also like to rearrange the label numbers so bv mirrors v etc.)

Yes, we should have this.  (Oh, and the JSON version can also be described in CDDL -- a bit shorter, as there is no need for the numeric labels.)

**Comment by cabo** [comment]
Independent of whether we include the CDDL, we have to answer the questions below:

``` CDDL
SenML = [+(base-obj, [*entry])]  ; is it *entry or +entry?

base-obj = {
    ? bn => text,       ; Base Name
    ? bt => numeric,    ; Base Time
    ? bu => text,       ; Base Units
    ? bv => numeric,    ; Base Value -- DO WE WANT TO ADD THIS?
    ? ver => uint,      ; Version
    * text => any,      ; (Extension)
}

entry = {
    ? n => tstr,        ; Name
    ? u => tstr,        ; Units
    ? ( v => numeric // ; Numeric Value
        sv => tstr //   ; String Value
        Bv => bool )    ; Boolean Value -- RENAME THIS THEN?
    ? s => numeric,     ; Value Sum
    ? t => numeric,     ; Time
    ? ut => numeric,    ; Update Time
}

numeric = number / decfrac

             ut  =  0
ver = -1     s   =  1
bn  = -2     n   =  2
bt  = -3     t   =  3
bu  = -4     u   =  4
bv  = -5     v   =  5
             sv  =  6
             Bv  =  7
```

**Comment by akeranen** [comment]
Can someone remind me why we need the CDDL? 

The base value does make sense. And as Cullen earlier commented, we could rename "bv" to "vb" and then "sv" to "vs" for consistency.

**Comment by cabo** [comment]
Do you "need" ABNF?  A toothbrush?

Neither is "needed", but it becomes a bit unhealthy without.

A formal notation encourages clear thinking.  Of course, that effect can be used during development and then the resulting specification kept secret, but that would give away the other benefit: a formal notation (if designed correctly) can communicate unambiguously.

(Re the clear thinking: I already identified the question whether measurement arrays can be empty or need at least one entry as one that the current English does not seem to answer.)

**Comment by akeranen** [comment]
OK, I see. But let's wait until the syntax is (more) stable and then add this if needed.

**Comment by fluffy** [comment]
close this as we have a new cddl2 branch with much better CDDL

**Pull request closed without merging**
